int a = 4, b = 5;
a= a + b;
Console.WriteLine(a+ " "+ b);
a = a - b;
Console.WriteLine(a + " " + b);
a= a * b;
Console.WriteLine(a + " " + b);
a = a / b;
Console.WriteLine(a + " " + b);
a = a % b;
Console.WriteLine(a + " " + b);
a = a | b;
Console.WriteLine(a + " " + b);
a = 4;
a = a ^ b;
Console.WriteLine(a + " " + b);
a = a & b;
Console.WriteLine(a + " " + b);